on:
  workflow_call:
  
jobs:
  release:
    name: Release Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Use Node (latest)
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Declare some variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
    - name: Bump up package
      run: npm version prerelease --no-git-tag-version --preid ${{ env.sha_short }}   
    - name: Publish
      run: sh scripts/publish-prerelease.sh
      env:
        REGISTRY_AUTH_TOKEN: ${{ secrets.VERDACCIO_REGISTRY_TOKEN_CANARY }}
        REGISTRY_URL: rg.verdaccio.org
